server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/ecom_docker?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
  application:
    name: MyDockerSimple


logging:
  level:
    root: INFO
