server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ecom?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update


logging:
  level:
    root: INFO
