server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecom?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
  application:
    name: MyDockerSimple

logging:
  level:
    root: INFO            

management:
  endpoints:
    shutdown:
      enabled: true
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5,0.7,0.95,0.99
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 10ms,100ms
