server:
  port: 9900

spring:
  datasource:
    url: jdbc:mysql://192.168.1.23:3316/ecom_docker?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
  application:
    name: MyDocker1Simple

logging:
  level:
    root: INFO
