version: "3.9"

services:

  db:
    image: mysql
    ports:
      - "3316:3316"
    expose:
      - 3316
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root


  demo1:
    build:
      context: .
      args:
        COLLECT: otel-collector
    depends_on:
      - db
      - otel-collector

    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=db
      - COLLECTOR=otel-collector

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/techstudy/tech/projects/SpringbootDockerDemo/ch6/prometheus.yml:/etc/prometheus/prometheus.yml


  otel-collector:
    depends_on:
      - prometheus
      - jaeger
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ --config=/etc/otel-collector-config.yaml ]
    ports:
      - 1888:1888 # pprof extension
      - 8889:8889 # Prometheus metrics exposed by the collector
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679
      - 8700:8700

  jaeger:
    depends_on:
      - prometheus
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
      - "8317:4317"
      - "8318:4318"

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 3000:3000